- name: install httpd and start the ansible.builtin.service
  hosts: frontend
  become: yes
  tasks: # list of tasks/modules/collections
  - name: installing httpd
    ansible.builtin.package:
      name: httpd
      state: present
  
  - name: start httpd ansible.builtin.service
    ansible.builtin.service:
      name: httpd
      state: started
      

