- name: install and start nginx service
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: latest
  - name: starting nginx services
    ansible.builtin.service:
      name: nginx
      state: started