- name: condition
  hosts: local
  connection: local
  vars:
    number: 5
  tasks:
  - name: the given number is less then 10 or not
    ansible.builtin.debug:
      msg: " Given number is: {{ number }} is then 10 "
    when: number < 10