- name: setup catelogue server
  hosts: catelogue
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      system: true
      shell: /sbin/nologin
      home: /app 

  - name: create a app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: downloade catalogue application
    ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip

  - name: extract catalouge application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
