- name: setup mangodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mangodb server
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and enabled mongodb service
    ansible.builtin.service:
      name: mongod 
      state: started
      enabled: yes

  - name: aloowing remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      
  - name: restart mongodb service
    ansible.builtin.service:
      name: mongod
      state: restarted